apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
spec:
  type: LoadBalancer
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80