apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example-deployment
spec:
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.23
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80